version: "3"
services:
  mongodb:
    image: mongo:4.2.9
    container_name: la_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./db_data/mongo:/data/db"
      # - "./data/mongo-entrypoint:/docker-entrypoint-initdb.d"
  server:
    image: la_server:latest
    container_name: la_server
    restart: always
    environment:
      - HTTP_PORT
      - MONGODB_ADDR
      - REDIS_ADDR
    depends_on:
      - mongodb
    ports:
      - "80:80"
